config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, skip: 'password'
  devise_for :users, skip: 'password', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # ユーザー
  get 'users/my_page', to: 'users#my_page', as: 'my_page'
  get 'users/my_page_edit', to: 'users#my_page_edit'
  get 'users/my_page_show', to: 'users#my_page_show'
  get 'users/:id', to: 'users#show', as: 'users_show'
  patch 'users/update', to: 'users#update'
  put 'users/update', to: 'users#update'

  # 投稿食事
  resources :post_foods do
    # コメント
    resources :food_comments, only: [:create, :destroy]
    # お気に入り
    resource :favorites, only: [:create, :destroy]
  end

  # 食事登録
  resources :food_regists, except: [:index, :destroy] do
    # 食事登録詳細
    resources :food_regist_shows, only: [:destroy]
  end

  # 食事登録カート
  delete 'food_regist_carts/destroy_all', to: 'food_regist_carts#destroy_all', as: 'food_regist_carts_destroy_all'
  resources :food_regist_carts, only: [:create, :destroy]

  # ホーム
  root 'homes#top'
  get 'about', to: 'homes#about'
  post 'guest', to: 'homes#new_guest'

  # 体重登録
  post 'weight_regist', to: 'weight_regists#create'

  # 検索
  get 'search', to: 'searches#search'

  # お気に入り一覧画面
  get 'favorites', to: 'favorites#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true

  has_many :food_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :food_regist_carts, dependent: :destroy
  has_many :post_foods, dependent: :destroy
  has_many :food_regists, dependent: :destroy
  attachment :profile_image

  with_options on: :step1 do
    validates :sex, presence: true
    validates :weight, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    validates :height, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    validates :exercise, presence: true
    validates :age, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  end

  with_options on: :step2 do
    validates :calorie, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    validates :protain, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    validates :fat, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    validates :carbon, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  end

  enum exercise: {do_noting: 0, once_or_twice_a_week: 1, two_or_three_times_a_week: 2,
                  three_or_five_times_a_week: 3, everyday: 4}
  enum sex: {male: 0, female: 1, other: 2}
  enum select_setting: {no_setting: 0, auto_setting: 1, manual_setting: 2}

  def target_calorie
    if sex == 'male'
      (male_daily_target_calorie * exercise_frequency).ceil
    elsif sex == 'femail'
      (female_daily_target_calorie * exercise_frequency).ceil
    else
      (other_daily_target_calorie * exercise_frequency).ceil
    end
  end

  # def target_calorie
  # case sex
  # when "male"
  #   (male_daily_target_calorie * exercise_frequency).ceil
  # when "femail"
  #   (female_daily_target_calorie * exercise_frequency).ceil
  # when "other"
  #   (other_daily_target_calorie * exercise_frequency).ceil
  # end
  # end

  def male_daily_target_calorie
    13.397 * weight + 4.799 * height - 5.677 * age + 88.362
  end

  def female_daily_target_calorie
    9.247 * weight + 3.098 * height - 4.33 * age + 447.593
  end

  def other_daily_target_calorie
    11.322 * weight + 3.949 * height - 5.00 * age + 267.978
  end

  # def exercise_frequency
  # case exercise
  # when "do_noting"
  #   1.2
  # when "once_or_twice_a_week"
  #   1.375
  # when "two_or_three_times_a_week"
  #   1.55
  # when "three_or_five_times_a_week"
  #   1.725
  # when "everyday"
  #   1.9
  # end
  # end

  def exercise_frequency
    if exercise == 'do_noting'
      1.2
    elsif exercise == 'once_or_twice_a_week'
      1.375
    elsif exercise == 'two_or_three_times_a_week'
      1.55
    elsif exercise == 'three_or_five_times_a_week'
      1.725
    elsif exercise == 'everyday'
      1.9
    end
  end

  def target_protain
    (weight * 2.2).ceil
  end

  def target_fat
    (target_calorie * 0.2 / 9).ceil
  end

  def target_carbon
    ((target_calorie - (target_protain * 4 + target_fat * 9)) / 4).ceil
  end

  def self.search(word)
    self.where(['last_name LIKE ? OR first_name LIKE ? ', "%#{word}%", "%#{word}%"])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    redirect_to my_page_path
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:my_page_edit]}

  # マイページ画面
  def my_page
    # カレンダーの定義
    @callender_food_regists = FoodRegist.where(user_id: current_user)
    # 今日の日付
    @day_params = Time.zone.today
    # 今日の食事内容のレコード定義
    @food_regists = FoodRegist.where(user_id: current_user, day: Time.zone.today)
    # 今日の食事内容の合計値レコードの定義
    food_regist = FoodRegist.where(day: Time.zone.today, user_id: current_user).pluck(:id)
    @food_regist_shows = FoodRegistShow.where(food_regist_id: food_regist)
    # 体重登録
    @weight_regist = WeightRegist.new
    @weight_regists = WeightRegist.where(user_id: current_user).pluck(:day, :weight)
    @weight_regist_base = WeightRegist.where(user_id: current_user).average(:weight)
  end

  # 特定の日のマイページ画面
  def my_page_show
    # カレンダーの定義
    @callender_food_regists = FoodRegist.where(user_id: current_user)
    # 押下されたカレンダーの日付
    @day_params = params[:format]
    # 特定の日の食事内容のレコード定義
    @food_regists = FoodRegist.where(user_id: current_user, day: @day_params)
    # 特定の日の食事内容の合計値レコードの定義
    food_regist = FoodRegist.where(day: @day_params, user_id: current_user).pluck(:id)
    @food_regist_shows = FoodRegistShow.where(food_regist_id: food_regist)
    # 体重登録
    @weight_regist = WeightRegist.new
    @weight_regists = WeightRegist.where(user_id: current_user).pluck(:day, :weight)
    @weight_regist_base = WeightRegist.where(user_id: current_user).average(:weight)
  end

  # 特定のユーザーの投稿食事一覧画面
  def show
    @user = User.find(params[:id])
    @post_foods = PostFood.where(user_id: params[:id]).page(params[:page]).reverse_order
    @food_regist_cart = FoodRegistCart.new
  end

  # マイページ編集画面
  def my_page_edit
    @user = current_user
  end

  # マイページ編集を更新する
  def update
    @user = current_user
    @user.select_setting = user_params[:select_setting]
    @user.save
    case @user.select_setting
    when 'no_setting'
      selected_user_params = {last_name: user_params[:last_name], first_name: user_params[:first_name],
                              email: user_params[:email], profile_image: user_params[:profile_image],
                              select_setting: user_params[:select_setting]}
      if @user.update(selected_user_params)
        redirect_to my_page_path
      else
        render :my_page_edit
      end
    when 'auto_setting'
      selected_user_params = {last_name: user_params[:last_name], first_name: user_params[:first_name],
                              email: user_params[:email], profile_image: user_params[:profile_image],
                              sex: user_params[:sex], weight: user_params[:weight], height: user_params[:height],
                              exercise: user_params[:exercise], age: user_params[:age],
                              select_setting: user_params[:select_setting]}
      @user.update(selected_user_params)
      if @user.valid?(:step1)
        redirect_to my_page_path
      else
        render :my_page_edit
        @user.select_setting = 'no_setting'
        @user.save
      end
    else
      @user.select_setting == 'manual_setting'
      selected_user_params = {last_name: user_params[:last_name], first_name: user_params[:first_name],
                              email: user_params[:email], profile_image: user_params[:profile_image],
                              calorie: user_params[:calorie], protain: user_params[:protain], fat: user_params[:fat],
                              carbon: user_params[:carbon], select_setting: user_params[:select_setting]}
      @user.update(selected_user_params)
      if @user.valid?(:step2)
        redirect_to my_page_path
      else
        render :my_page_edit
        @user.select_setting = 'no_setting'
        @user.save
      end
    end
  end

  # ユーザー認証
  def ensure_correct_user
    @user = User.find(params[:format])
    if current_user.id != @user.id
      redirect_to post_foods_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :email, :profile_image, :sex, :weight, :height, :exercise,
                                 :age, :calorie, :protain, :fat, :carbon, :select_setting)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_my_page.html.erb
<div class ="container">
  <div class="mx-auto">
    <h2 class="my-5" id="page-title">マイページ</h2>
    <% if weight_regist_error.present? %>
    <%= render "layouts/errors", resource: weight_regist_error %>
    <% end %>
    <div class="d-flex">
      <div class="text-center p-3 w-25" style="background-color: #EEEEEE; border-radius: 20px;">
        <div>
        <%= attachment_image_tag current_user, :profile_image, size: "50x50", fallback: "no_image.jpg", style: "border-radius: 20px;" %>
        <%= current_user.last_name %>さん
        </div>
        <div>
          <%= link_to users_my_page_edit_path(current_user), class: 'btn btn-success mt-2' do %>
            <i class="fas fa-user-edit"></i>プロフィール編集
          <% end %>
        </div>
      </div>
      <div>
        <div class="text-center py-4 ml-3" style="background-color: #EEEEEE; border-radius: 20px;">
          <%= form_with model:weight_regist, url: weight_regist_path, local: true do |f| %>
          <div>
            <%= f.label '今日の体重', class: 'control-label' %>
            <div class="w-50 d-flex offset-3 w-50">
              <%= f.text_field :weight, class: 'form-control', size: "30x10" %><span id="unit">kg</span>
              <% if WeightRegist.where(user_id: current_user, day: Date.today).present? %>
                <%= f.submit '登録済み', class: 'btn btn-success ml-3', disabled: true %>
              <% else %>
                <%= f.submit '登録', class: 'btn btn-success ml-3' %>
              <% end %>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    <!--目標値-->
    <div class="my-5 target">
      <h4 class="text-center">1日の消費カロリーとマクロ栄養素の目標値</h4>
      <% if current_user.select_setting == "no_setting" %>
      <div class="my-3">
        <h5 class="text-center">目標値は設定されていません</h5>
        <div class="text-center">
          <%= link_to '目標値を設定する', users_my_page_edit_path(current_user), class: 'btn btn-success' %>
        </div>
      </div>
      <% elsif current_user.select_setting == "auto_setting" %>
      <table class='table text-center table-bordered w-75 mx-auto table-light' style='table-layout: fixed;'>
        <thead>
          <tr>
            <td>kcal</td>
            <td>たんぱく質</td>
            <td>脂質</td>
            <td>炭水化物</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= current_user.target_calorie %></td>
            <td><%= current_user.target_protain %></td>
            <td><%= current_user.target_fat %></td>
            <td><%= current_user.target_carbon %></td>
          </tr>
        </tbody>
      </table>
      <div class="text-right" style="font-size: 5px;">※「自動で設定する」の場合、ハリス・ベネディクト方程式(改良版)を使って基礎代謝量・1日の消費カロリーを計算しています。</div>
      <% else current_user.select_setting == "manual_setting" %>
      <table class='table text-center table-bordered w-75 mx-auto table-light' style='table-layout: fixed;'>
        <thead>
          <tr>
            <td>kcal</td>
            <td>たんぱく質</td>
            <td>脂質</td>
            <td>炭水化物</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= current_user.calorie %></td>
            <td><%= current_user.protain %></td>
            <td><%= current_user.fat %></td>
            <td><%= current_user.carbon %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
    <!--食事内容-->
    <div class="my-5 food_regist">
      <h4 class="text-center"><%= day_params.to_time.strftime('%Y年%-m月%-d日') %>の食事内容</h4>
      <table class='table text-center table-bordered table-light' style='table-layout: fixed;'>
        <thead>
          <tr>
            <td></td>
            <td>kcal</td>
            <td>たんぱく質</td>
            <td>脂質</td>
            <td>炭水化物</td>
            <td></td>
          </tr>
        </thead>
        <% food_regists.each do |food_regist| %>
        <tbody>
          <tr>
            <td><%= food_regist.timing %> </td>
            <td><%= food_regist.food_regist_shows.aggregate(:calorie) %></td>
            <td><%= food_regist.food_regist_shows.aggregate(:protain) %></td>
            <td><%= food_regist.food_regist_shows.aggregate(:fat) %></td>
            <td><%= food_regist.food_regist_shows.aggregate(:carbon) %></td>
            <td>
              <%= link_to '詳細', food_regist_path(food_regist), class: 'btn btn-success' %>
              <%= link_to '編集', edit_food_regist_path(food_regist), class: 'btn btn-success' %>
            </td>
            <% end %>
          </tr>
          <tfoot>
            <tr>
              <td>合計</td>
              <td>
                <%= food_regist_shows.aggregate(:calorie) %>
              </td>
              <td>
                <%= food_regist_shows.aggregate(:protain) %>
              </td>
              <td>
                <%= food_regist_shows.aggregate(:fat) %>
              </td>
              <td>
                <%= food_regist_shows.aggregate(:carbon) %>
              </td>
              <td></td>
            </tr>
          </tfoot>
        </tbody>
      </table>
    </div>
    <!--カレンダー-->
    <%= month_calendar events: callender_food_regists do |date, callender_food_regists| %>
      <%= date.day %>
      <% sum = 0 %>
      <% callender_food_regists.each do |callender_food_regist| %>
        <div>
          <% sum += callender_food_regist.food_regist_shows.aggregate(:calorie) %>
        </div>
      <% end %>
      <% unless sum == 0 %>
        総カロリー：<%= link_to sum, users_my_page_show_path(date) %>kcal
      <% end %>
    <% end %>
    <% if @weight_regists.present? %>
    <div>
      <h4 class="text-center"><%= Date.today.month %>月の体重推移</h4>
      <%= line_chart @weight_regists, xmin: Date.today.beginning_of_month, xmax: Date.today.end_of_month,
          min: (@weight_regist_base.ceil - 10), max: (@weight_regist_base.ceil + 10 ), xtitle: "日付", ytitle: "体重(kg)" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/my_page.html.erb
<%= render 'users/my_page' ,
callender_food_regists: @callender_food_regists,
day_params: @day_params,
food_regists: @food_regists,
food_regist_shows: @food_regist_shows,
weight_regist: @weight_regist,
callender_weight_regists: @callender_weight_regists,
weight_regist_error: @weight_regist_error %>

app/views/users/my_page_edit.html.erb
<div class ="container">
  <div class="mx-auto">
    <h2 class="my-5" id="page-title">プロフィール編集</h2>
      <div class = "form-horizontal">
      <%= form_with model:@user, url: users_update_path, local: true do |f| %>
      <%= render "layouts/errors", resource: @user %>
      <div class = "form-group row">
        <%= f.label :profile_image, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.attachment_field :profile_image, class: "col-sm-3 control-label text-right" %>
      </div>
      <div class="form-group row">
        <%= f.label :last_name, class: "col-sm-3 control-label text-right offset-sm-1" %><br />
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control col-sm-2" %>

        <%= f.label :first_name, class: "col-sm-1 control-label text-right" %><br />
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control col-sm-2" %>
      </div>
      <div class = "form-group row">
        <%= f.label :email, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :email, autofocus: true, class: "form-control col-sm-5" %>
      </div>
      <div class="text-right">
      <%= link_to 'パスワード変更と退会', edit_user_registration_path, class: "btn btn-primary" %>
      </div>
      <div class="text-center">
        <h4 class="my-5 my-page-setting">1日の消費カロリーとマクロ栄養素の設定について</h4>
      </div>
    <div class ="row" style="justify-content: center;">
<!--設定しないフォーム-->
        <div class="form-group col-sm-2">
          <div>
            <%= f.radio_button :select_setting, "no_setting" %>設定しない
          </div>
        </div>
<!--自動で設定するフォーム-->
      <div class="form-group col-sm-4 auto-set mr-3">
        <%= f.radio_button :select_setting, "auto_setting" %>自動で設定する
        <div>
          <%= f.label :sex %>
          <%= f.radio_button :sex, "male" %>男性
          <%= f.radio_button :sex, "female" %>女性
          <%= f.radio_button :sex, "other" %>その他
        </div>
        <div class ="d-flex my-3">
          <%= f.label :weight, class: "control-label text-right" %>
          <%= f.text_field :weight, class: "form-control col-sm-3 ml-5" %><span id="unit">　kg</span>
        </div>
        <div class ="d-flex mb-3">
          <%= f.label :height, class: "control-label" %>
          <%= f.text_field :height, class: "form-control col-sm-3 ml-5" %><span id="unit">　cm</span>
        </div>
        <div class ="d-flex mb-3">
          <%= f.label :exercise, class: "control-label mr-2" %>
          <%= f.select :exercise, User.exercises.keys.map {|k| [I18n.t("enums.user.exercise.#{k}"), k]}, value: @user.exercise %>
        </div>
        <div class ="d-flex">
          <%= f.label :age, class: "control-label" %>
          <%= f.text_field :age, class: "form-control col-sm-3 ml-5" %><span id="unit">　歳</span>
        </div>
      </div>
<!--自分で設定するフォーム-->
      <div class="form-group col-sm-4 manual-set">
         <%= f.radio_button :select_setting, "manual_setting" %>自分で設定する
         <div class ="d-flex my-3">
          <%= f.label :calorie, class: "control-label mr-2" %>
          <%= f.text_field :calorie, class: "form-control col-sm-3" %><span id="unit">　kcal</span>
        </div>
        <div class ="d-flex my-3">
          <%= f.label :protain, class: "control-label mr-4" %>
          <%= f.text_field :protain, class: "form-control col-sm-3" %><span id="unit">　g</span>
        </div>
        <div class ="d-flex my-3">
          <%= f.label :fat, class: "control-label mr-5" %>
          <%= f.text_field :fat, class: "form-control col-sm-3 ml-4" %><span id="unit">　g</span>
        </div>
        <div class ="d-flex my-3">
          <%= f.label :carbon, class: "control-label mr-4" %>
          <%= f.text_field :carbon, class: "form-control col-sm-3 ml-3" %><span id="unit">　g</span>
        </div>
      </div>
    </div>
  </div>
  <div class = "row mt-5">
    <%= f.submit '更新する', class: "btn btn-success d-block mx-auto btn-lg" %>
  </div>
  <% end %>
  </div>
</div>

app/views/users/my_page_show.html.erb
<%= render 'users/my_page' ,
callender_food_regists: @callender_food_regists,
day_params: @day_params,
food_regists: @food_regists,
food_regist_shows: @food_regist_shows,
weight_regist: @weight_regist,
callender_weight_regists: @callender_weight_regists,
weight_regist_error: @weight_regist_error %>

app/views/users/show.html.erb
<div class="container">
  <h2 class="my-5" id="page-title"><%= @user.last_name %>さん投稿一覧</h2>
  <%= render "post_foods/index", post_foods: @post_foods, food_regist_cart: @food_regist_cart %>
</div>