config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, skip: 'password'
  devise_for :users, skip: 'password', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # ユーザー
  get 'users/my_page', to: 'users#my_page', as: 'my_page'
  get 'users/my_page_edit', to: 'users#my_page_edit'
  get 'users/my_page_show', to: 'users#my_page_show'
  get 'users/:id', to: 'users#show', as: 'users_show'
  patch 'users/update', to: 'users#update'
  put 'users/update', to: 'users#update'

  # 投稿食事
  resources :post_foods do
    # コメント
    resources :food_comments, only: [:create, :destroy]
    # お気に入り
    resource :favorites, only: [:create, :destroy]
  end

  # 食事登録
  resources :food_regists, except: [:index, :destroy] do
    # 食事登録詳細
    resources :food_regist_shows, only: [:destroy]
  end

  # 食事登録カート
  delete 'food_regist_carts/destroy_all', to: 'food_regist_carts#destroy_all', as: 'food_regist_carts_destroy_all'
  resources :food_regist_carts, only: [:create, :destroy]

  # ホーム
  root 'homes#top'
  get 'about', to: 'homes#about'
  post 'guest', to: 'homes#new_guest'

  # 体重登録
  post 'weight_regist', to: 'weight_regists#create'

  # 検索
  get 'search', to: 'searches#search'

  # お気に入り一覧画面
  get 'favorites', to: 'favorites#index'
end

app/models/food_regist.rb
class FoodRegist < ApplicationRecord
  belongs_to :user
  has_many :food_regist_shows, dependent: :destroy

  validates :day, presence: true
  validates :timing, presence: true

  enum timing: {朝食: 0, 昼食: 1, 夕食: 2, 間食: 3}

  def start_time
    self.day
  end
end

app/controllers/food_regists_controller.rb
class FoodRegistsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:show, :edit, :update]}
  # 食事登録画面
  def new
    @food_regist_carts = FoodRegistCart.where(user_id: current_user.id)
    @food_regist = FoodRegist.new
  end

  # 食事登録詳細画面
  def show
    @food_regist = FoodRegist.find(params[:id])
    @food_regist_shows = FoodRegistShow.where(food_regist_id: @food_regist.id)
  end

  # 食事登録を確定する
  def create
    food_regist = FoodRegist.new(food_regist_params)
    food_regist.user_id = current_user.id
    if food_regist.save
      @food_regist_carts = current_user.food_regist_carts
      @food_regist_carts.each do |food_regist_cart|
        food_regist_show = FoodRegistShow.new(food_regist_id: food_regist.id)
        food_regist_show.post_food_id = food_regist_cart.post_food_id
        food_regist_show.save
      end
      @food_regist_carts.destroy_all
      redirect_to my_page_path
    else
      @food_regist_carts = FoodRegistCart.where(user_id: current_user.id)
      @food_regist = FoodRegist.new
      @error_food_regist = food_regist
      render :new
    end
  end

  # 食事登録編集画面
  def edit
    @food_regist = FoodRegist.find(params[:id])
    @food_regist_shows = FoodRegistShow.where(food_regist_id: @food_regist.id)
  end

  # 食事登録編集を更新する
  def update
    food_regist = FoodRegist.find(params[:id])
    if food_regist.update(food_regist_params)
      redirect_to my_page_path
    else
      @food_regist = FoodRegist.find(params[:id])
      @food_regist_shows = FoodRegistShow.where(food_regist_id: @food_regist.id)
      render :edit
    end
  end

  # ユーザー認証
  def ensure_correct_user
    food_regist = FoodRegist.find(params[:id])
    if current_user.id != food_regist.user_id
      redirect_to my_page_path
    end
  end

  private

  def food_regist_params
    params.require(:food_regist).permit(:day, :timing)
  end
end

app/helpers/food_regists_helper.rb
module FoodRegistsHelper
end

app/views/food_regists/edit.html.erb
<div class="container">
  <div class="mx-auto">
    <h2 class="my-5">食事登録編集画面</h2>
    <%= form_with(model:@food_regist, url: food_regist_path, local: true) do |f| %>
<!--日付入力欄-->
    <div class="d-flex my-5">
      <div class ="w-25">
        <%= f.label :day, class: 'control-label' %>
        <%= f.date_field :day, class: 'form-control' %>
      </div>
<!--タイミング入力欄-->
      <div class="ml-5">
        <%= f.label :timing, class: 'control-label d-block' %>
        <span class="mr-3"><%= f.radio_button :timing, '朝食' %>朝食</span>
        <span class="mr-3"><%= f.radio_button :timing, '昼食' %>昼食</span>
        <span class="mr-3"><%= f.radio_button :timing, '夕食' %>夕食</span>
        <span class="mr-3"><%= f.radio_button :timing, '間食' %>間食</span>
      </div>
    </div>
<!--食事内容の詳細表示-->
    <table class='table text-center table-bordered'>
      <thead>
        <tr>
          <td></td>
          <td>kcal</td>
          <td>たんぱく質</td>
          <td>脂質</td>
          <td>炭水化物</td>
          <td></td>
        </tr>
      </thead>
      <% @food_regist_shows.each do |food_regist_show| %>
      <tbody>
        <tr>
          <td class="text-left"><%= food_regist_show.post_food.name %></td>
          <td><%= food_regist_show.post_food.calorie %></td>
          <td><%= food_regist_show.post_food.protain %></td>
          <td><%= food_regist_show.post_food.fat %></td>
          <td><%= food_regist_show.post_food.carbon %></td>
          <td><%= link_to '削除', food_regist_food_regist_show_path(@food_regist, food_regist_show), method: :delete, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
        <tfoot>
          <tr>
            <td>合計</td>
            <td>
              <%= @food_regist_shows.aggregate(:calorie) %>
            </td>
            <td>
              <%= @food_regist_shows.aggregate(:protain) %>
            </td>
            <td>
              <%= @food_regist_shows.aggregate(:fat) %>
            </td>
            <td>
              <%= @food_regist_shows.aggregate(:carbon) %>
            </td>
            <td></td>
          </tr>
        </tfoot>
      </tbody>
    </table>
    <% unless @food_regist_shows.count == 0 %>
      <%= f.submit '登録を確定する', class: "btn btn-success d-block mx-auto btn-lg my-5" %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/food_regists/new.html.erb
<div class="container">
  <div class="mx-auto">
    <h2 class="my-5" id="page-title">食事登録</h2>
    <% if @error_food_regist %>
      <%= render 'layouts/errors', resource: @error_food_regist %>
    <% end %>
    <% unless @food_regist_carts.present? %>
      <h3>現在登録された食事はありません。</h3>
    <% else %>
    <%= form_with(model:@food_regist, url: food_regists_path, local: true) do |f| %>
<!--日付入力欄-->
    <div class="d-flex my-5">
      <div class ="w-25">
        <%= f.label :day, class: 'control-label' %>
        <%= f.date_field :day, class: 'form-control' %>
      </div>
<!--タイミング入力欄-->
      <div class="ml-5">
        <%= f.label :timing, class: 'control-label d-block' %>
        <span class="mr-3"><%= f.radio_button :timing, '朝食' %>朝食</span>
        <span class="mr-3"><%= f.radio_button :timing, '昼食' %>昼食</span>
        <span class="mr-3"><%= f.radio_button :timing, '夕食' %>夕食</span>
        <span class="mr-3"><%= f.radio_button :timing, '間食' %>間食</span>
      </div>
      <div class="ml-auto mt-5">
        <%= link_to '全て削除', food_regist_carts_destroy_all_path, method: :delete, class: "btn btn-danger pull-right" %>
      </div>
    </div>
<!--食事内容の詳細表示-->
    <table class='table text-center table-bordered'>
      <thead>
        <tr>
          <td></td>
          <td>kcal</td>
          <td>たんぱく質</td>
          <td>脂質</td>
          <td>炭水化物</td>
          <td></td>
        </tr>
      </thead>
      <% @food_regist_carts.each do |food_regist_cart| %>
      <tbody>
        <tr>
          <td class="text-left"><%= food_regist_cart.post_food.name %></td>
          <td><%= food_regist_cart.post_food.calorie %></td>
          <td><%= food_regist_cart.post_food.protain %></td>
          <td><%= food_regist_cart.post_food.fat %></td>
          <td><%= food_regist_cart.post_food.carbon %></td>
          <td><%= link_to '削除', food_regist_cart_path(food_regist_cart), method: :delete, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
        <tfoot>
          <tr>
            <td>合計</td>
            <td>
              <%= @food_regist_carts.aggregate(:calorie) %>
            </td>
            <td>
              <%= @food_regist_carts.aggregate(:protain) %>
            </td>
            <td>
              <%= @food_regist_carts.aggregate(:fat) %>
            </td>
            <td>
              <%= @food_regist_carts.aggregate(:carbon) %>
            </td>
            <td></td>
          </tr>
        </tfoot>
      </tbody>
    </table>
    <%= f.submit '登録を確定する', class: "btn btn-success d-block mx-auto btn-lg my-5" %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/food_regists/show.html.erb
<div class="container">
  <div class="mx-auto">
    <h2 class="my-5" id="page-title">食事登録詳細画面</h2>
    <% unless @food_regist_shows.present? %>
      <h3>現在登録された食事はありません。</h3>
    <% else %>
<!--日付欄-->
    <div class="d-flex my-5">
      <div class ="w-25 p-3" style="background-color: #CCFFFF; border-radius: 20px;">
        日付：<%= @food_regist.day %>
      </div>
<!--タイミング入力欄-->
      <div class="ml-5 p-3" style="background-color: #CCFFFF; border-radius: 20px;">
        <%= @food_regist.timing %>
      </div>
    </div>
<!--食事内容の詳細表示-->
    <table class='table text-center table-bordered'>
      <thead>
        <tr>
          <td></td>
          <td>kcal</td>
          <td>たんぱく質</td>
          <td>脂質</td>
          <td>炭水化物</td>
        </tr>
      </thead>
      <% @food_regist_shows.each do |food_regist_show| %>
      <tbody>
        <tr>
          <td class="text-left"><%= food_regist_show.post_food.name %></td>
          <td><%= food_regist_show.post_food.calorie %></td>
          <td><%= food_regist_show.post_food.protain %></td>
          <td><%= food_regist_show.post_food.fat %></td>
          <td><%= food_regist_show.post_food.carbon %></td>
          <% end %>
        </tr>
        <tfoot>
          <tr>
            <td>合計</td>
            <td>
              <%= @food_regist_shows.aggregate(:calorie) %>
            </td>
            <td>
              <%= @food_regist_shows.aggregate(:protain) %>
            </td>
            <td>
              <%= @food_regist_shows.aggregate(:fat) %>
            </td>
            <td>
              <%= @food_regist_shows.aggregate(:carbon) %>
            </td>
          </tr>
        </tfoot>
      </tbody>
    </table>
    <div>
      <%= link_to '編集する', edit_food_regist_path(@food_regist), class: "btn btn-success d-block mx-auto btn-lg my-5 w-25" %>
    </div>
  <% end %>
  </div>
</div>