config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, skip: 'password'
  devise_for :users, skip: 'password', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # ユーザー
  get 'users/my_page', to: 'users#my_page', as: 'my_page'
  get 'users/my_page_edit', to: 'users#my_page_edit'
  get 'users/my_page_show', to: 'users#my_page_show'
  get 'users/:id', to: 'users#show', as: 'users_show'
  patch 'users/update', to: 'users#update'
  put 'users/update', to: 'users#update'

  # 投稿食事
  resources :post_foods do
    # コメント
    resources :food_comments, only: [:create, :destroy]
    # お気に入り
    resource :favorites, only: [:create, :destroy]
  end

  # 食事登録
  resources :food_regists, except: [:index, :destroy] do
    # 食事登録詳細
    resources :food_regist_shows, only: [:destroy]
  end

  # 食事登録カート
  delete 'food_regist_carts/destroy_all', to: 'food_regist_carts#destroy_all', as: 'food_regist_carts_destroy_all'
  resources :food_regist_carts, only: [:create, :destroy]

  # ホーム
  root 'homes#top'
  get 'about', to: 'homes#about'
  post 'guest', to: 'homes#new_guest'

  # 体重登録
  post 'weight_regist', to: 'weight_regists#create'

  # 検索
  get 'search', to: 'searches#search'

  # お気に入り一覧画面
  get 'favorites', to: 'favorites#index'
end

app/models/post_food.rb
class PostFood < ApplicationRecord
  belongs_to :user
  has_many :food_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :food_regist_carts, dependent: :destroy
  has_many :food_regist_shows, dependent: :destroy
  attachment :food_image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :calorie, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :protain, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :fat, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :carbon, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(word)
    self.where(['name LIKE ?', "%#{word}%"])
  end
end

app/controllers/post_foods_controller.rb
class PostFoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  # 投稿食事一覧画面
  def index
    @post_foods = PostFood.page(params[:page]).reverse_order
    @food_regist_cart = FoodRegistCart.new
  end

  # 投稿食事詳細画面
  def show
    @post_food = PostFood.find(params[:id])
    @food_comment = FoodComment.new
    @food_regist_cart = FoodRegistCart.new
  end

  # 新規投稿食事画面
  def new
    @post_food = PostFood.new
  end

  # 新規投稿する
  def create
    @post_food = PostFood.new(post_food_params)
    @post_food.user_id = current_user.id
    if @post_food.save
      redirect_to post_foods_path
    else
      render :new
    end
  end

  # 投稿食事編集画面
  def edit
    @post_food = PostFood.find(params[:id])
  end

  # 投稿食事の編集を更新する
  def update
    @post_food = PostFood.find(params[:id])
    if @post_food.update(post_food_params)
      redirect_to post_food_path(@post_food)
    else
      render :edit
    end
  end

  # 投稿を削除する
  def destroy
    @post_food = PostFood.find(params[:id])
    @post_food.destroy
    redirect_to post_foods_path
  end

  # ユーザー認証
  def ensure_correct_user
    @post_food = PostFood.find(params[:id])
    if current_user.id != @post_food.user_id
      redirect_to post_foods_path
    end
  end

  private

  def post_food_params
    params.require(:post_food).permit(:name, :introduction, :food_image, :calorie, :protain, :fat, :carbon)
  end
end

app/helpers/post_foods_helper.rb
module PostFoodsHelper
end

app/views/post_foods/_index.html.erb
<div class="row">
  <% post_foods.each do |post_food| %>
  <div class="col-lg-3 col-md-4 col-sm-6" id="post_food_flame">
    <div class="d-flex">
    <%= link_to users_show_path(post_food.user), class: "text-left px-0" do %>
    <%= post_food.user.last_name %>さんの投稿
    <% end %>
    <% if post_food.food_comments.present? %>
      <% if post_food.food_comments.average(:score) > 0.5 %>
        <h5 class="ml-auto p-1" style="color: red; background-color: yellow; border-radius: 20px;">高評価</h5>
      <% end %>
    <% end %>
    </div>
    <h6>食事名：<%= post_food.name.truncate(20) %></h6>
    <div>
      <%= link_to post_food_path(post_food) do %>
      <%= attachment_image_tag post_food, :food_image, size: "250x250", fallback: "no_image.jpg", style: "border-radius: 20px;" %>
      <% end %>
    </div>
    <h6 class ="mt-3">＜1食あたり＞</h6>
    <table class="table-bordered" id="table_index">
      <thead>
        <tr>
          <th class="text-center table-success">カロリー</th>
          <td class="text-center bg-light"><%= post_food.calorie %></td>
        </tr>
        <tr>
          <th class="text-center table-success">たんぱく質</th>
          <td class="text-center bg-light"><%= post_food.protain %></td>
        </tr>
        <tr>
          <th class="text-center table-success">脂質</th>
          <td class="text-center bg-light"><%= post_food.fat %></td>
        </tr>
        <tr>
          <th class="text-center table-success">炭水化物</th>
          <td class="text-center bg-light"><%= post_food.carbon %></td>
        </tr>
      </thead>
    </table>
    <div class ="my-2">
      <%= form_for (food_regist_cart) do |f| %>
      <%= f.hidden_field :post_food_id, :value => post_food.id %>
      <%= f.submit '食事登録に追加する', class: "btn btn-info d-block btn-lg mx-auto" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
<div>
  <%= paginate post_foods %>
</div>

app/views/post_foods/edit.html.erb
<div class="container">
  <div class="mx-auto">
    <h2 class="my-5" id="page-title">投稿食事編集</h2>
    <div class = "form-horizontal">
      <%= form_with model:@post_food, local: true do |f| %>
      <%= render "layouts/errors", resource: @post_food %>
      <div class = "form-group row">
        <%= f.label :food_image, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.attachment_field :food_image, class: "col-sm-3 control-label text-right" %>
      </div>
      <div class = "form-group row">
        <%= f.label :name, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :name, autofocus: true, class: "form-control col-sm-5", rows:"5" %>
      </div>
      <div class = "form-group row">
        <%= f.label :introduction, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_area :introduction, autofocus: true, class: "form-control col-sm-5" %>
      </div>
      <div class = "row my-4">
        <h5 class = "offset-sm-3">＜1食あたり＞</h5>
      </div>
      <div class = "form-group row">
        <%= f.label :calorie, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :calorie, autofocus: true, class: "form-control col-sm-1" %><span id="unit">　kcal</span>
      </div>
      <div class = "form-group row">
        <%= f.label :protain, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :protain, autofocus: true, class: "form-control col-sm-1" %><span id="unit">　g</span>
      </div>
      <div class = "form-group row">
        <%= f.label :fat, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :fat, autofocus: true, class: "form-control col-sm-1" %><span id = "unit">　g</span>
      </div>
      <div class = "form-group row">
        <%= f.label :carbon, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :carbon, autofocus: true, class: "form-control col-sm-1" %><span id = "unit">　g</span>
      </div>
      <div class = "row mt-5">
        <%= f.submit '更新する', class: "btn btn-success d-block mx-auto btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/post_foods/index.html.erb
<div class="container">
  <h2 class="my-5" id="page-title">投稿一覧</h2>
  <%= render "searches/form" %>
  <%= render "post_foods/index", post_foods: @post_foods, food_regist_cart: @food_regist_cart %>
</div>

app/views/post_foods/new.html.erb
<div class="container">
  <div class="mx-auto">
    <h2 class="my-5" id="page-title">新規投稿</h2>
    <div class = "form-horizontal">
      <%= form_with model:@post_food, local: true do |f| %>
      <%= render "layouts/errors", resource: @post_food %>
      <div class = "form-group row">
        <%= f.label :food_image, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.attachment_field :food_image, class: "col-sm-3 control-label text-right" %>
      </div>
      <div class = "form-group row">
        <%= f.label :name, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :name, autofocus: true, class: "form-control col-sm-5", rows:"5" %>
      </div>
      <div class = "form-group row">
        <%= f.label :introduction, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_area :introduction, autofocus: true, class: "form-control col-sm-5" %>
      </div>
      <div class = "row my-4">
        <h5 class = "offset-sm-3">＜1食あたり＞</h5>
      </div>
      <div class = "form-group row">
        <%= f.label :calorie, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :calorie, autofocus: true, class: "form-control col-sm-1" %><span id="unit">　kcal</span>
      </div>
      <div class = "form-group row">
        <%= f.label :protain, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :protain, autofocus: true, class: "form-control col-sm-1" %><span id="unit">　g</span>
      </div>
      <div class = "form-group row">
        <%= f.label :fat, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :fat, autofocus: true, class: "form-control col-sm-1" %><span id = "unit">　g</span>
      </div>
      <div class = "form-group row">
        <%= f.label :carbon, class: "col-sm-3 control-label text-right offset-sm-1" %>
        <%= f.text_field :carbon, autofocus: true, class: "form-control col-sm-1" %><span id = "unit">　g</span>
      </div>
      <div class = "row mt-5">
        <%= f.submit '新規登録', class: "btn btn-success d-block mx-auto btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/post_foods/show.html.erb
<div class="container mt-5" style="background-color: #E6FFE9; border-radius: 20px;">
<!--食事名とお気に入りボタン-->
  <div class ="row mx-2">
    <h2 class="my-5"><%= @post_food.name %></h2>
    <div class="ml-auto" id="post_food_favorite">
      <%= render 'favorites/index', post_food: @post_food %>
    </div>
  </div>
<!--投稿情報-->
  <div class="row mx-2">
    <div class="col-sm-6 col-xs-12">
      <%= attachment_image_tag @post_food.user, :profile_image, size: "50x50", fallback: "no_image.jpg", style: "border-radius: 20px;" %>
      <%= link_to users_show_path(@post_food.user), class: "text-left px-0" do %>
      <%= @post_food.user.last_name %>さんの投稿
      <% end %>
      <div>
        <%= attachment_image_tag @post_food, :food_image, size: "400x400", fallback: "no_image.jpg", style: "border-radius: 20px;" %>
      </div>
    </div>
    <div class="col-sm-5 col-xs-12">
      <div class ="my-3">
        <%= form_with model:@food_regist_cart, url: food_regist_carts_path, local: true do |f| %>
        <%= f.hidden_field :post_food_id, :value => @post_food.id %>
        <%= f.submit '食事登録に追加する', class: "btn btn-info d-block btn-lg" %>
        <% end %>
      </div>
      <div>
        <h6 class ="mt-2">＜1食あたり＞</h6>
        <table class="table-bordered" id="table_show">
          <thead>
            <tr>
              <th class="text-center table-success" style="height: 60px;">カロリー（kcal）</th>
              <td class="text-center bg-light"><%= @post_food.calorie %></td>
            </tr>
            <tr>
              <th class="text-center table-success" style="height: 60px;">たんぱく質（g）</th>
              <td class="text-center bg-light"><%= @post_food.protain %></td>
            </tr>
            <tr>
              <th class="text-center table-success" style="height: 60px;">脂質（g）</th>
              <td class="text-center bg-light"><%= @post_food.fat %></td>
            </tr>
            <tr>
              <th class="text-center table-success" style="height: 60px;">炭水化物（g）</th>
              <td class="text-center bg-light"><%= @post_food.carbon %></td>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
  <div class="d-flex">
    <div class ="row d-block mt-4 mx-2 introduction">
      <div class="col-sm-12">
        <p>
          <%= safe_join(@post_food.introduction.split("\n"),tag(:br)) %>
        </p>
      </div>
    </div>
    <div class="mt-5">
      <% if @post_food.user_id == current_user.id %>
        <%= link_to edit_post_food_path(@post_food), class: "btn btn-success mx-5" do %>
          <i class="far fa-edit"></i>編集する
        <% end %>
        <%= link_to post_food_path(@post_food), method: :delete, class: "btn btn-danger" do %>
          <i class="fas fa-trash-alt"></i> 投稿を削除する
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div id="food_comments_index">
  <%= render "food_comments/index", post_food: @post_food, food_comment: @food_comment %>
</div>