config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, skip: 'password'
  devise_for :users, skip: 'password', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # ユーザー
  get 'users/my_page', to: 'users#my_page', as: 'my_page'
  get 'users/my_page_edit', to: 'users#my_page_edit'
  get 'users/my_page_show', to: 'users#my_page_show'
  get 'users/:id', to: 'users#show', as: 'users_show'
  patch 'users/update', to: 'users#update'
  put 'users/update', to: 'users#update'

  # 投稿食事
  resources :post_foods do
    # コメント
    resources :food_comments, only: [:create, :destroy]
    # お気に入り
    resource :favorites, only: [:create, :destroy]
  end

  # 食事登録
  resources :food_regists, except: [:index, :destroy] do
    # 食事登録詳細
    resources :food_regist_shows, only: [:destroy]
  end

  # 食事登録カート
  delete 'food_regist_carts/destroy_all', to: 'food_regist_carts#destroy_all', as: 'food_regist_carts_destroy_all'
  resources :food_regist_carts, only: [:create, :destroy]

  # ホーム
  root 'homes#top'
  get 'about', to: 'homes#about'
  post 'guest', to: 'homes#new_guest'

  # 体重登録
  post 'weight_regist', to: 'weight_regists#create'

  # 検索
  get 'search', to: 'searches#search'

  # お気に入り一覧画面
  get 'favorites', to: 'favorites#index'
end

app/views/layouts/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました。以下ご確認お願いいたします。</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-4 mt-5" id='footer'>
  <div class="container">
    <div class="mx-auto">
      <h6 class='text-center text-dark'>©︎Copyright 2020 We Need Muscle, inc. All right reserved.</h6>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" id="header">
    <nav class='nav navbar-nav navbar-left' >
      <h2>
        <%= link_to root_path, class: "nav-item" do %><%= image_tag('logo.png', id: "logo") %><% end %>
      </h2>
    </nav>
    <nav class="navbar navbar-expand-lg">
      <ul class="nav navbar-nav navbar-right">
        <!--ログイン後のheader-->
        <% if user_signed_in? %>
          <li class="text-dark">ようこそ、<%= current_user.last_name %>さん！</li>
          <li><%= link_to " About", about_path, class: "fas fa-file-alt nav-item header-btn" %></li>
          <li><%= link_to " 食事登録", new_food_regist_path, class: "fas fa-utensils nav-item header-btn" %></li>
          <li><%= link_to " 投稿一覧", post_foods_path, class: "fas fa-folder-open nav-item header-btn" %></li>
          <li><%= link_to " マイページ", my_page_path, class: "fas fa-user nav-item header-btn" %></li>
          <li><%= link_to " 新規投稿", new_post_food_path, class: "fas fa-pen-fancy nav-item header-btn" %></li>
          <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-item header-btn" %></li>
        <% else %>
          <!--ログイン前のheader-->
          <li><%= link_to " About", about_path, class: "fas fa-file-alt nav-item header-btn" %></li>
          <li><%= link_to " 新規登録", new_user_registration_path, class: "fas fa-user-plus nav-item header-btn" %></li>
          <li><%= link_to " ログイン", new_user_session_path, class: "fas fa-sign-in-alt nav-item header-btn" %></li>
          <li><%= link_to " ゲストログイン", guest_path, class: "fas fa-user-check nav-item header-btn", method: :post %></li>
        <% end %>
      </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeNeedMuscle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <script src="https://kit.fontawesome.com/f70bfcd248.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>